version: "3.5"

services:

  git:
    container_name: git
    hostname: git
    build:
      context: ./
    restart: always
    ports:
    - "50022:22/tcp"
    volumes:
    - repositories:/repositories

volumes:
  repositories:
