version: "3.5"

services:

  radicale: 
    container_name: radicale 
    hostname: radicale
    build:
      context: ./      
    restart: always    
    ports:
    - "5232:5232/tcp"    
    volumes:
    - config:/etc/radicale
    - data:/var/lib/radicale

volumes:
  config:
  data:
