version: "3.5"

services:

  git-server:
  
    build:
      context: ./
      
    restart: always
    
    ports:
    - "50022:22"
    
    volumes:
    - repositories:/repositories
    
volumes:
  repositories:
