version: "3.5"

services:

  syncthing:
    container_name: syncthing
    hostname: docker-syncthing
    build:
      context: ./sources
    restart: always
    network_mode: "host"
    volumes:
    - data:/var/syncthing

volumes:
  data:
